apiVersion: v1
kind: Service
metadata:
  name: service-abonnement
spec:
  selector:
    app: service-abonnement
  type: NodePort
  ports:
    - name: http
      port: 8083
      nodePort: 31003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-abonnement
spec:
  selector:
    matchLabels:
      app: service-abonnement
  replicas: 1
  template:
    metadata:
      labels:
        app: service-abonnement
    spec:
      containers:
        - name: server
          image: yuliamos/service-abonnement
          ports:
            - name: http
              containerPort: 8083
          env:
            - name: USER_URL
              value: http://service-identity:8081/users
            - name: CLASS_URL
              value: http://service-class:8082/classes

---